### ISSUE TITLE
[1.0.8] Bug: Recent sounds showing muffled sounds

### ISSUE THREAD

**Issue by GenericUser7134** [Lyfts/ExtremeSoundMuffler-Legacy#11]
The Recent sound list is also showing the Muffled sound list.
![image](https://github.com/user-attachments/assets/1f7c510c-add3-4297-8f42-ce278b6e59a0)

**Comment by Lyfts** [comment]
Somewhat fixed in the latest release https://www.curseforge.com/minecraft/mc-mods/extreme-sound-muffler-legacy/files/5574586.
It will continue display some muffled sounds but only the recent ones as opposed to all of them.
