### ISSUE TITLE
Some interface issues

### ISSUE THREAD

**Issue by GedeonGrays** [Lyfts/ExtremeSoundMuffler-Legacy#2]
Hello o/

The mod works and it's amazingly user-friendly (especially nice that it's client-side), but there are a few things worth adjusting.

1. Long text in tips moves to the left at any GUI Scale except Small: https://imgur.com/a/7dnQ3sv
Perhaps you could implement a line break like word wrap in Notepad++, so that the line length adjusts to the GUI Scale.
2. When you hold down the Shift key in the interface, the “Clear recent sounds list” button icon is overlaid on top of the “Delete Muffled List” button icon, rather than replacing it. This is a bit confusing: https://imgur.com/a/kogKQ9C

**Comment by Lyfts** [comment]
Thanks for reporting this! It has been fixed in the latest release https://github.com/Lyfts/ExtremeSoundMuffler-Legacy/releases/tag/1.0.3

**Comment by GedeonGrays** [comment]
> Thanks for reporting this! It has been fixed in the latest release https://github.com/Lyfts/ExtremeSoundMuffler-Legacy/releases/tag/1.0.3

Super! Works perfectly! Thanks for the quick fix.
