### ISSUE TITLE
1.12.2 Version

### ISSUE THREAD

**Issue by kurrycat2004** [Lyfts/ExtremeSoundMuffler-Legacy#7]
Would you be open to supporting a 1.12.2 version too? I could PR it if you don't want to do it yourself, either on a different branch, or on the same one using something like unimined to support multiple versions in the same repo

**Comment by Lyfts** [comment]
Sure I'd be down for that, I made a 1.12.2 branch that you're more than welcome to pr to. I can probably also look into it myself at some point.

**Comment by Lyfts** [comment]
https://www.curseforge.com/minecraft/mc-mods/extreme-sound-muffler-legacy/files/5497728
